[build]
builder = "nixpacks"
buildCommand = "cd order-backend && cp package-railway.json package.json && npm install"

[deploy]
startCommand = "cd order-backend && node auth-server-production.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.variables]
NODE_ENV = "production"