[build]
buildCommand = "cp package-simple.json package.json && npm install"

[deploy]
startCommand = "node simple-server.js"
    variables:
      NODE_ENV: production
      PORT: ${{RAILWAY_PORT}}
      JWT_SECRET: ${{JWT_SECRET}}
      EMAIL_USER: ${{EMAIL_USER}}
      EMAIL_PASS: ${{EMAIL_PASS}}
      MSG91_API_KEY: ${{MSG91_API_KEY}}
      RAZORPAY_KEY_ID: ${{RAZORPAY_KEY_ID}}
      RAZORPAY_KEY_SECRET: ${{RAZORPAY_KEY_SECRET}}

networking:
  serviceDomains:
    - domain: your-app.railway.app